---
apiVersion: v1
kind: Secret
metadata:
  name: schmidtjonathan1-poi-backend-app-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/rhdh23-demo/schmidtjonathan1-backend-gitops
